# Use Python 3.9 as the base image
FROM python:3.11-slim

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to /app
COPY requirements.txt .

# Install the dependencies from the requirements.txt file
RUN pip install -r requirements.txt
RUN pip install "Flask[async]"

# Copy the webhook server code to /app
COPY openai-chat-tbot.py .

# Set the environment variables for the API token and the port number
ENV GPT_BOT_TOKEN=<Your Telegram Bot Token>
ENV OPENAI_API_KEY=<Your OpenAI API Key>
ENV PORT=8080
ENV AUTHORIZED_USERS=""
ENV BOT_PERSONALITY=Friendly

# Expose the port number for cloudrun
EXPOSE 8080

# Run the webhook server code when the container starts
CMD ["python", "openai-chat-tbot.py"]